#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

process_game() {
    # Delete unnecessary files
    rm -rf gamedata/*.exe gamedata/*.dll gamedata/.gitkeep
    echo "Removed unecessary files"
    
    # Copy assets from gamedata folder
    if [ -d "gamedata" ]; then
        mv gamedata/* .
        echo "Moved assets from gamedata to GAMEDIR."
        sleep 1
        rm -rf gamedata
        echo "Removed gamedata directory."
        sleep 1
    fi
        
    # Check if the data.win file exists and apply xdelta
    if [ -f "data.win" ]; then
        echo "Applying xdelta patch"
        output=$(xdelta3 -d -s "data.win" -f "./tools/patches/idol_sfx.xdelta" "game.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "data.win"
        else
            echo "Failed to apply patch"
            echo "$output"
            exit 1
        fi
    fi
        
    sleep 3
    
    #compress_audio
	
    # Final completion message
    echo "Patching process complete!"
}

compress_audio() {
    # Compress audio
        echo "Compressing audio. The process will take 5-10 minutes."     
        mkdir -p "$TMPDIR"
        # Run the compression tool
        echo "Running gmKtool.py with parameters..."
        PYTHON=$(which python3)
        $PYTHON ./tools/gmKtool.py -vvv -m 1024 -b 64 -d "$TMPDIR" "$GAMEDIR/game.droid"

        if [ $? -eq 0 ]; then
            echo "Compression completed successfully."
            mv "$TMPDIR/"* "$GAMEDIR"
            echo "Moved compressed files to $GAMEDIR."
            rm "$GAMEDIR/compress.txt"
            echo "Removed compress.txt from $GAMEDIR."
            rmdir "$TMPDIR"
            echo "Temporary directory $TMPDIR removed."
            echo "Audio compression applied successfully."
        else
            echo "Audio compression failed."
            echo "Cleaning up temporary directory $TMPDIR."
            rm -rf "$TMPDIR"
        fi
}

# Call the function
process_game
